global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: 
        - 'prometheus:9090'

  - job_name: 'demo'
    static_configs: 
    - targets:
      - 'demosvc-10000:10000'
      - 'demosvc-10001:10001'
      - 'demosvc-10002:10002'

  - job_name: 'node'
    static_configs:
    - targets:
      - 'node-exporter:9100'