- name: Install Node-Exporter Container
  hosts: labsys
  remote_user: sysadmin
  become: yes

  tasks:
  - name: Create Node-Exporter Volume
    community.docker.docker_volume:
      driver: "local"
      name: node-exporter-storage

  - name: Create Node-Exporter Container
    community.docker.docker_container:
      name: node-exporter
      state: started
      image: prom/node-exporter:latest
      restart_policy: always
      ports:
        - 9100:9100
      volumes:
        - /proc:/host/proc:ro       
        - /sys:/host/sys:ro       
        - /:/rootfs:ro  

  - name: Add to promnet
    community.docker.docker_network:
      name: promnet
      connected:
        - node-exporter
      appends: true