- name: Install and configure DockerCE
  hosts: labsys
  remote_user: sysadmin
  become: true

  tasks: 

    - name: Install DockerCE
      ansible.builtin.import_role:
        name: labrats_work.modules_ansible.docker

    - name: Create promnet
      community.docker.docker_network:
        name: promnet